### ISSUE TITLE
Cityscapes pretrained models download about google drive

### ISSUE THREAD

**Issue by XinBow99** [fast-vid2vid/fast-vid2vid#1]
Hi Author, it's a perfect project! 
I'm running this project, the Cityscapes pretrained models need access rights of google driver when i request, can you share this file? 
Thanks you!

**Comment by fast-vid2vid** [comment]
Hi @XinBow99 , the pre-trained model for Cityscapes is corrupt, and we will update it soon.

**Comment by XinBow99** [comment]
hi @fast-vid2vid, it's possible to testing by use nVidia vid2vid's Cityscapes model?

**Comment by fast-vid2vid** [comment]
No. We have modified some structures of the original models, and the inference process is quite different from the original one. Please wait for the update.

> hi @fast-vid2vid, it's possible to testing by use nVidia vid2vid's Cityscapes model?

**Comment by XinBow99** [comment]
Ok, Thanks!

**Comment by fast-vid2vid** [comment]
hi @XinBow99 , we have uploaded a new pre-trained model for Cityscapes.
