### ISSUE TITLE
Training Problems

### ISSUE THREAD

**Issue by kjgfxzp** [fast-vid2vid/fast-vid2vid#2]
Hi, I'm a student working on GAN and this's an awesome project. But I got some problems when I tried to train the model using the following command line:
```python train.py --name test1 --label_nc 0 --loadSize 1024 --n_scales_spatial 2 --gpu_ids 0,1,2,3 --batchSize 4```
And I just got an error like this:
<img width="811" alt="截屏2022-07-21 下午4 45 48" src="https://user-images.githubusercontent.com/67938920/181749290-16a1947b-628d-4894-ac4c-82cf1c196c9b.png">
Please help me.

**Comment by fast-vid2vid** [comment]
Hi @kjgfxzp , we have removed the option 'fp16'. You can skip this to run this training code. But this code is to train the original vid2vid. Our KD code will be released this month.

**Comment by zhanghongyong123456** [comment]
> 你好@kjgfxzp，我们删除了选项“fp16”。您可以跳过此步骤来运行此训练代码。但这段代码是训练原始的vid2vid。我们的 KD 代码将于本月发布。

请问是这样修改吗，我发现缺少args 参数列表，我该如何修改
![image](https://github.com/fast-vid2vid/fast-vid2vid/assets/48466610/65e7612f-9be8-490e-bfc9-5662bcf61674)

when  run  vid2vid  
![image](https://github.com/fast-vid2vid/fast-vid2vid/assets/48466610/b60af548-c7a3-43fa-b2c3-812a7da74843)
