### ISSUE TITLE
FVD computation

### ISSUE THREAD

**Issue by indigopyj** [fast-vid2vid/fast-vid2vid#5]
How did you compute FVD score in your paper?

Could you please share me some code for FVD?

**Comment by fast-vid2vid** [comment]
hi @indigopyj , we compute the FVD with this [paper's](https://arxiv.org/abs/1812.01717) code.

**Comment by indigopyj** [comment]
> hi @indigopyj , we compute the FVD with this [paper's](https://arxiv.org/abs/1812.01717) code.

Thanks! I have one more questions. How many videos and how many frames per video  did you used for FVD?

**Comment by fast-vid2vid** [comment]
> > hi @indigopyj , we compute the FVD with this [paper's](https://arxiv.org/abs/1812.01717) code.
> 
> Thanks! I have one more question. How many videos and how many frames per video did you use for FVD?

We used all testing videos and 28 frames (2 for initial frames) per video for calculating FVD.
