### ISSUE TITLE
Training resources？

### ISSUE THREAD

**Issue by kaigelee** [fast-vid2vid/fast-vid2vid#6]
Thanks for your great work.
I would like to ask what is the minimum hardware configuration required for training the model? e.g., 2*3090?

Also, does graphics card memory affect effect?

**Comment by fast-vid2vid** [comment]
hi, @kaigelee  We trained and tested our model mainly with V100 (32GB). We have also conducted some small experiments with 1080Ti (10GB). Maybe you can try these experiments with 3090.
