### ISSUE TITLE
i3d model used in tkd training

### ISSUE THREAD

**Issue by ChennyTech** [fast-vid2vid/fast-vid2vid#7]
Hello, Thank you for your nice work!

I am training tkd student model and I am curious about the i3d model checkpoint you used in tkd training.
Could you let me know the i3d network repository and the checkpoints you used?

Thank you

**Comment by fast-vid2vid** [comment]
Hi @ChennyTech , we use I3D pre-trained model in the PyTorch version. Here is a useful repository.
https://github.com/piergiaj/pytorch-i3d

**Comment by ghost** [comment]
> Hi @ChennyTech , we use I3D pre-trained model in the PyTorch version. Here is a useful repository. https://github.com/piergiaj/pytorch-i3d

Thank you for your answer! By the way, I noticed that there are four checkpoint files in that repository. 
Could you advise me on which specific file I should use?

**Comment by fast-vid2vid** [comment]
hi @themis0888 , the uploaded checkpoints are organized by the specific task, such as sketch2face, and segmentation2city. Please select the one according to your task.
